name: Validate Code Owner Before Workflow Execution

on:
  workflow_dispatch:

jobs:
  validate-codeowner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate if Actor is a Code Owner
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const codeOwnersResponse = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: ".github/CODEOWNERS",
            });

            const codeOwnersContent = Buffer.from(codeOwnersResponse.data.content, 'base64').toString();
            console.log("CODEOWNERS Content:\n", codeOwnersContent);

            const actor = context.actor.toLowerCase();

            const isCodeOwner = codeOwnersContent.toLowerCase().includes(actor);

            if (!isCodeOwner) {
              throw new Error(`User ${actor} is not a Code Owner. Workflow execution is not allowed.`);
            }

            console.log(`User ${actor} is a valid Code Owner. Proceeding with the workflow.`);