name: Create and Merge Pull Request from DEV to MAIN

on:
  workflow_dispatch:  # Para ejecutarlo manualmente desde la pesta침a Actions

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-22.04

    # 1) Otorga permisos de escritura al GITHUB_TOKEN para que pueda crear y actualizar PRs
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Paso A: Clonar el repositorio (historial completo)
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Paso B: Configurar Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Paso C: Crear o actualizar Pull Request de dev -> main
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          # Usar el GITHUB_TOKEN por defecto (sin 'token:' usa secrets.GITHUB_TOKEN)
          branch: dev      # Rama de origen
          base: main       # Rama de destino
          commit-message: "Auto: Fusionar DEV en MAIN"
          title: "PR autom치tica de DEV a MAIN"
          body: |
            Este Pull Request fue generado autom치ticamente para fusionar
            la rama dev en main.
          # Si NO quieres que se genere una nueva rama en cada ejecuci칩n,
          # no agregues branch-suffix, ni random ni timestamp.

      # Paso D: Depurar (opcional)
      - name: Debug PR
        if: steps.create_pr.outputs.pull-request-url != ''
        run: |
          echo "Pull Request URL: ${{ steps.create_pr.outputs.pull-request-url }}"
          echo "Pull Request Number: ${{ steps.create_pr.outputs.pull-request-number }}"

      # Paso E: Auto-Merge (opcional)
      - name: Enable Auto-Merge
        if: steps.create_pr.outputs.pull-request-url != ''
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge_label: 'automerge-dev-to-main'