name: Create PR and Auto-Merge

on:
  workflow_dispatch:

jobs:
  create-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create PR with GH CLI
        id: create_pr
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          PR_JSON=$(gh pr create \
            --base main \
            --head dev \
            --title "Fusionar dev en main" \
            --body "Este PR se creó con GH CLI" \
            --json number,url)

          echo "PR_JSON=$PR_JSON"

          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.number')
          echo "::set-output name=pr_number::$PR_NUMBER"

          # (Opcional) Añadir etiqueta "automerge"
          gh pr edit $PR_NUMBER --add-label automerge

      - name: Enable Auto-Merge (pascalgn)
        if: steps.create_pr.outputs.pr_number != ''
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge_label: automerge