name: Create PR and Auto-Merge

on:
  workflow_dispatch:

jobs:
  create-and-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      # Paso 1: Check out el repo (opcional pero recomendable)
      - name: Checkout
        uses: actions/checkout@v3

      # Paso 2: Instalar GitHub CLI (gh) en el runner
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # Paso 3: Crear el Pull Request con GH CLI
      - name: Create PR with GH CLI
        run: |
          # 3a) Autenticar la CLI usando el GITHUB_TOKEN
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          # 3b) Crear el PR y asignar la etiqueta 'automerge'
          gh pr create \
            --base main \
            --head dev \
            --title "Fusionar dev a main" \
            --body "Pull Request creado con GH CLI" \
            --label automerge

      # Paso 4: Auto-merge con pascalgn/automerge-action
      - name: Enable Auto-Merge
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: 'automerge'
          MERGE_METHOD: 'merge'