name: Create PR, Approve, and Auto-Merge

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch from which you want to create the PR (e.g., dev)"
        required: true
        default: "dev"

jobs:
  create-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Paso 2: Autenticar GitHub CLI
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      # Paso 3: Crear la Pull Request con una etiqueta específica
      - name: Create Pull Request
        id: create_pr
        run: |
          PR_OUTPUT=$(gh pr create \
            --base main \
            --head ${{ github.event.inputs.target_branch }} \
            --title "Merge ${{ github.event.inputs.target_branch }} into main" \
            --body "This PR was created automatically by the workflow." \
            --label automerge)
          echo "PR created: $PR_OUTPUT"

          # Extraer el número del PR
          PR_URL=$(echo "$PR_OUTPUT" | grep -Eo 'https://[^ ]+')
          PR_NUMBER="${PR_URL##*/}"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV

      # Paso 4: Aprobar la PR automáticamente
      - name: Approve Pull Request
        run: |
          echo "Approving the PR #${{ env.PR_NUMBER }}..."
          gh pr review --approve ${{ env.PR_URL }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-merge:
    needs: create-pr
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      # Loguear metadata de la PR
      - name: Log Metadata
        run: |
          echo "PR created by github-actions[bot]"
          echo "PR URL: ${{ env.PR_URL }}"
          echo "PR Number: ${{ env.PR_NUMBER }}"

      # Habilitar Auto-Merge para PRs con la etiqueta 'automerge'
      - name: Enable auto-merge for PRs with 'automerge' label
        run: gh pr merge --auto --merge "https://github.com/${{ github.repository }}/pull/${{ env.PR_NUMBER }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}