name: Create and Merge Pull Request from DEV to MAIN

on:
  workflow_dispatch:

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-22.04

    # 1) Otorga permisos de escritura al GITHUB_TOKEN para que pueda crear y actualizar PRs
    permissions:
      contents: write
      pull-requests: write

    steps:
      # Paso A: Clonar el repositorio con todo el historial
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Paso B: Configurar Git (committer por defecto)
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Paso C: Crear (o actualizar) el Pull Request
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          # Se puede omitir si quieres usar el GITHUB_TOKEN por defecto:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev    # Rama de origen
          base: main     # Rama destino
          commit-message: "Auto: Actualización de DEV a MAIN"
          title: "PR automática de DEV a MAIN"
          body: |
            Este Pull Request fue generado automáticamente
            para sincronizar los cambios de `dev` a `main`.
          # Si NO quieres que se genere una rama nueva cada vez, NO incluyas branch-suffix

      # Paso D: Debug (opcional) - Muestra la URL y número del PR si se creó
      - name: Debug PR Information
        if: steps.create_pr.outputs.pull-request-url != ''
        run: |
          echo "PR URL: ${{ steps.create_pr.outputs.pull-request-url }}"
          echo "PR Number: ${{ steps.create_pr.outputs.pull-request-number }}"

      # Paso E: Auto-Merge (opcional) - Fusiona el PR automáticamente si todo está bien
      - name: Enable Auto-Merge
        if: steps.create_pr.outputs.pull-request-url != ''
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          merge_label: 'automerge-dev-to-main'