name: Create PR from dev to main using GitHub CLI

on:
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Create Pull Request from dev to main
        run: |
          # Autenticarse con el GITHUB_TOKEN
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

          gh pr create \
            --head dev \
            --base main \
            --title "Fusionar dev a main" \
            --body "Pull Request creado desde la rama dev sin force push."