name: Create and Merge Pull Request from DEV to MAIN

on:
  workflow_dispatch:

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Verify Changes in DEV
      run: |
        git fetch origin dev
        git log origin/main..origin/dev

    - name: Create Pull Request
      id: create_pr
      uses: peter-evans/create-pull-request@v5
      with:
        branch: dev
        base: main
        commit-message: "Auto: Actualizaci칩n de DEV a MAIN"
        title: "PR autom치tica de DEV a MAIN"
        body: |
          Este Pull Request fue generado autom치ticamente para pasar los cambios de `dev` a `main`.
        labels: 'automerge-dev-to-main'

    - name: Debug PR Information
      run: |
        echo "PR URL: ${{ steps.create_pr.outputs.pull-request-url }}"
        echo "PR Number: ${{ steps.create_pr.outputs.pull-request-number }}"

    - name: Verify PR Labels
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/${{ github.repository }}/issues/${{ steps.create_pr.outputs.pull-request-number }}/labels

    - name: Enable Auto-Merge
      if: steps.create_pr.outputs.pull-request-url != '' # Solo si el PR se cre칩 correctamente
      uses: pascalgn/automerge-action@v0.15.6
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        merge_label: 'automerge-dev-to-main'