name: Create PR and Approve

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch from which you want to create the PR (e.g., dev)"
        required: true
        default: "dev"

jobs:
  create-pr-and-approve:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Pull Request
        id: create_pr
        run: |
          PR_OUTPUT=$(gh pr create \
            --base main \
            --head ${{ github.event.inputs.target_branch }} \
            --title "Merge ${{ github.event.inputs.target_branch }} into main" \
            --body "This PR was created automatically by the workflow.")
          echo "PR created: $PR_OUTPUT"

          # Extraer el número del PR
          PR_URL=$(echo "$PR_OUTPUT" | grep -Eo 'https://[^ ]+')
          PR_NUMBER="${PR_URL##*/}"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Approve Pull Request
        run: |
          echo "Approving the PR as ${{ github.actor }}..."
          gh pr review ${{ env.PR_NUMBER }} --approve

      # Paso 6: Fusionar el Pull Request
      - name: Merge Pull Request
        run: |
          PR_NUMBER=${{ env.PR_NUMBER }}
          echo "Fusionando el PR #$PR_NUMBER..."
          gh pr merge $PR_NUMBER --merge --admin
